# Project information
site_name: watsonx Orchestrate workshop
site_url: https://arrow-ai-lab.github.io/workshop-watsonx-orchestrate
site_author: Arrow AI Lab

# Repository
repo_name: workshop-watsonx-orchestrate
repo_url: https://github.com/arrow-ai-lab/workshop-watsonx-orchestrate

# Navigation
nav:
  - Introduction: README.md
  - Preparation: 
    - Create your IBMid: ibmid/README.md
    - Provision your environments: environment/README.md
    - Get the required files: getfiles/README.md
  - Workshop:
    - Create AI assistant: part-1/README.md
    - Create AI-guided action: part-2/README.md
    - Create GenAI Skill for email body generation: part-3/README.md
    - Create GenAI Skill for email title generation: part-4/README.md
    - Publishing the GenAI Skills: part-5/README.md

# Copyright
copyright: Copyright &copy; 2025 Arrow AI Lab

# Theme
theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode

# Extensions
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true



#   font:
#     text: IBM Plex Sans
#     code: IBM Plex Mono
#   icon:
#     logo: material/library
#   logo: images/ibm-blue-background.png
#   features:
#     - navigation.tabs
#     #- navigation.instant
#   palette:
#     scheme: default
#     primary: blue
#     accent: blue

# # Plugins
# plugins:
#   - search
# #  - social

# # Customization
# extra:
#   social:
#     - icon: fontawesome/brands/github
#       link: https://github.com/ibm
#     - icon: fontawesome/brands/twitter
#       link: https://twitter.com/ibmdeveloper
#     - icon: fontawesome/brands/linkedin
#       link: https://www.linkedin.com/company/ibm/
#     - icon: fontawesome/brands/youtube
#       link: https://www.youtube.com/user/developerworks
#     - icon: fontawesome/brands/dev
#       link: https://dev.to/ibmdeveloper

# # Extensions
# markdown_extensions:
#   - abbr
#   - admonition
#   - attr_list
#   - def_list
#   - footnotes
#   - meta
#   - toc:
#       permalink: true
#   - pymdownx.arithmatex:
#       generic: true
#   - pymdownx.betterem:
#       smart_enable: all
#   - pymdownx.caret
#   - pymdownx.critic
#   - pymdownx.details
#   - pymdownx.emoji:
#       emoji_index: !!python/name:materialx.emoji.twemoji
#       emoji_generator: !!python/name:materialx.emoji.to_svg
#   - pymdownx.highlight
#   - pymdownx.inlinehilite
#   - pymdownx.keys
#   - pymdownx.mark
#   - pymdownx.smartsymbols
#   - pymdownx.snippets:
#       check_paths: true
#   - pymdownx.superfences:
#       custom_fences:
#         - name: mermaid
#           class: mermaid
#           format: !!python/name:pymdownx.superfences.fence_code_format
#   - pymdownx.tabbed
#   - pymdownx.tasklist:
#       custom_checkbox: true
#   - pymdownx.tilde
